### ISSUE TITLE
iframe in lecture template triggers revealjs template slides to open as multiple tabs in browser 

### ISSUE THREAD

**Issue by cynthiahqy** [numbats/monash-quarto-presentation#1]
iframe code:
![image](https://user-images.githubusercontent.com/29718979/221732909-8b0b4dcb-5ce6-4cea-b87b-bba36468e73b.png)

tabs that open upon rendering (either via button in RStudio or command line `quarto render`) -- the revealjs quarto webpage + all the slides in the revealjs example deck:
![image](https://user-images.githubusercontent.com/29718979/221733068-aff403d8-26da-433c-a621-4b4ef26e9ec2.png)

Fencing the html code does not seem to help...
- https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/12-html-block/

````md
```{=html}
<iframe src="https://quarto.org/docs/presentations/revealjs/" width="100%" height="100%">

</iframe>
```
````

**Comment by cynthiahqy** [comment]
Still happens if you change the link:
![image](https://user-images.githubusercontent.com/29718979/221733882-4ebc7848-3b91-4d4e-b665-7340b7981e7f.png)

Or if you switch from the `monash-revealjs` format to `revealjs`
![image](https://user-images.githubusercontent.com/29718979/221734308-ff5d5474-8d82-4e6e-bc3c-394a7326d77d.png)

**Comment by cynthiahqy** [comment]
Lodged issue: https://github.com/quarto-dev/quarto-cli/issues/4557

**Comment by cynthiahqy** [comment]
@TengMCing tracked the issue to rendering with "Preview in Viewer Pane" feature activated whilst the source .qmd file is also open in RStudio. Temporary fix -- select "Preview in Window" instead.

**Comment by cderv** [comment]
Hi ! 

I believe this is a known issue in IDE  solved already in https://github.com/rstudio/rstudio/issues/12494 for next release. Probably already available in daily - please try. 

Still not perfect though and next steps is tracked in https://github.com/rstudio/rstudio/issues/12766 but maybe current fix is already better for you. 

Hope it helps

**Comment by cynthiahqy** [comment]
Thanks @cderv! Just tried the latest daily build (2023.03.0+377) and the issue doesn't occur.
